### ISSUE TITLE
v1.x.0 -> v1.10.1 has a breaking change

### ISSUE THREAD

**Issue by bkspace** [uptrace/uptrace-js#130]
Just a quick request that in future breaking changes are not included in MINOR version updates, as this caused us a production issue this morning.

**Comment by vmihailenco** [comment]
>Just a quick request that in future breaking changes are not included in MINOR version updates

Agreed :+1: 

We've released v1.10 only yesterday so I hoped it is okay to make last minute change in v1.10.1...

**Comment by vmihailenco** [comment]
To clarity, OpenTelemetry introduced this breaking change in v1.10 as a part of [this commit](https://github.com/open-telemetry/opentelemetry-js/pull/3460). So Otel doesn't follow semver too...
